name: Build And Release

on:
  push:
    tags: [ 'v*' ]

jobs:
  BuildRelease:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            fetch-depth: 0

        - name: Grant Execute Permission for gradlew
          run: chmod +x gradlew

        - name: Setup Java
          uses: actions/setup-java@v4
          with:
            java-version: '17'
            distribution: 'oracle'

        - name: Setup Gradle
          uses: gradle/actions/setup-gradle@v4

        - name: Signing Configuration
          run: |
            echo "signing.keyAlias=${{ secrets.SIGNING_KEY_ALIAS }}" > signature.properties
            echo "signing.storePassword=${{ secrets.SIGNING_STORE_PASSWORD }}" >> signature.properties
            echo "signing.keyPassword=${{ secrets.SIGNING_KEY_PASSWORD }}" >> signature.properties
            base64 --decode <<< "${{secrets.JKS_BASE64}}" > keystore.jks
            echo "signing.storeFile=keystore.jks" >> signature.properties

        - name: Build
          run: ./gradlew --no-daemon app:assembleRelease

        - name: Release
          uses: softprops/action-gh-release@v2
          if: startsWith(github.ref, 'refs/tags/')
          with: 
            tag_name: ${{ github.ref }}
            generate_release_notes: true
            files: |
              app/build/outputs/apk/release/*.apk


              